name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Namaskar Swami"
      - name: print greeting2
        run: echo "Abhari aahe swami"
